server:
  port: 0
  forward-headers-strategy: framework

  app:
    storage:
      path: ${user.home}/.ijse/eca/tickets

spring:
  application:
    name: ticket-service

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true